USE_RESISTANCE = False
FIRST_TO_X_WINS = 100  # 2 = Best of 3, 5 = Best of 9
GAIN_LOSE_SANITY = False
STARTING_SANITY = 45
USE_STAGGER = True
COMBAT_VERBOSE = False
SHOW_BONUSES = True
FULL_DEBUG = False
