from combant_info import Sinner, Skill, Effect, Condition
from effects import EffectTrigger, EffectDetails, EffectCondition
from sin_types import Sin
from statuses import StatusType

sinners = {
    "LCB Sinner Yi Sang": Sinner("LCB Sinner Yi Sang", 147, 4, 8, 36, 28, [50, -25, 0], [60, 30],
                                 [Skill("Deflect", Sin.GLOOM, 0, 3, 7, 1, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.SINKING)]]),
                                  Skill("End-stop Stab", Sin.ENVY, 1, 4, 4, 2, [], [[], [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.SINKING),
                                                                               Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT, 1, status=StatusType.SINKING)]]),
                                  Skill("Enjamb", Sin.SLOTH, 0, 6, 1, 3, [], [[], [], [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.FRAGILE, condition=[Condition(EffectCondition.TARGET_HAS_LESS_THAN_SP, condition_amount=0)])]])]),
    "LCB Sinner Sinclair": Sinner("LCB Sinner Sinclair", 121, 3, 7, 26, 38, [-25, 50, 0], [70, 40, 20],
                                  [Skill("Downward Swing", Sin.PRIDE, 0, 3, 7, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.RUPTURE)]]),
                                   Skill("Halberd Combo", Sin.WRATH, 0, 4, 2, 3, [Effect(EffectTrigger.ClASH_WIN, EffectDetails.RAISE_ATTACK_DAMAGE_MULT, 30)], []),
                                   Skill("Ravaging Cut", Sin.ENVY, 0, 5, 2, 3, [Effect(EffectTrigger.ClASH_WIN, EffectDetails.GAIN_STATUS, 1, status=StatusType.ATTACK_POWER_UP)], [])]),
    "LCB Sinner Ryoshu": Sinner("LCB Sinner Ryoshu", 134, 3, 6, 28, 36, [-25, 0, 50], [70, 40, 20],
                                [Skill("Paint", Sin.GLUTTONY, 0, 3, 7, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_NEXT_TURN, 2, status=StatusType.POISE)]]),
                                 Skill("Splatter", Sin.LUST, 0, 4, 4, 2, [], [[Effect(EffectTrigger.BEFORE_HIT, EffectDetails.COIN_DMG_MULT, 30, condition=[Condition(EffectCondition.TARGET_TAKEN_DAMAGE)])],
                                                                    [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.COIN_DMG_MULT, 30, condition=[Condition(EffectCondition.TARGET_TAKEN_DAMAGE)])]]),
                                 Skill("Brushstroke", Sin.PRIDE, 0, 5, 2, 3, [Effect(EffectTrigger.COMBAT_START, EffectDetails.GAIN_STATUS, 2, status=StatusType.SLASH_DAMAGE_UP)], [])]),
    "LCB Sinner Rodion": Sinner("LCB Sinner Rodion", 159, 2, 5, 31, 33, [-25, 50, 0], [65, 35, 15],
                                [Skill("Strike Down", Sin.GLUTTONY, 0, 3, 7, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.BLEED)]]),
                                 Skill("Axe Combo", Sin.PRIDE, 0, 4, 4, 2, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.BLEED)],
                                                                     [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.BLEED)]]),
                                 Skill("Slay", Sin.WRATH, 0, 2, 2, 4, [Effect(EffectTrigger.ON_USE, EffectDetails.SKILL_POWER, 1, condition=[Condition(EffectCondition.SELF_HAS_LESS_THAN_SP, condition_amount=0)])],
                                       [[], [], [], [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.COIN_DMG_MULT, 20, condition=[Condition(EffectCondition.TARGET_HAS_STATUS_OF_AMOUNT, condition_status=StatusType.BLEED, condition_amount=6)])]])]),
    "LCB Sinner Outis": Sinner("LCB Sinner Outis", 120, 3, 7, 26, 38, [-25, 0, 50], [70, 40, 20],
                               [Skill("Pulled Blade", Sin.SLOTH, 1, 3, 2, 3, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.RUPTURE)]]),
                                Skill("Backslash", Sin.PRIDE, 0, 4, 4, 2, [], [[Effect(EffectTrigger.BEFORE_HIT, EffectDetails.COIN_DMG_MULT, 20, condition=[Condition(EffectCondition.SPEED_IS_HIGHER)])],
                                                                    [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.COIN_DMG_MULT, 20, condition=[Condition(EffectCondition.SPEED_IS_HIGHER)])]]),
                                Skill("Piercing Thrust", Sin.GLOOM, 1, 6, 14, 1, [Effect(EffectTrigger.ON_USE, EffectDetails.RAISE_ATTACK_DAMAGE_MULT, 20, condition=[Condition(EffectCondition.TARGET_ABOVE_HP, condition_amount=50)])], [])]),
    "LCB Sinner Meursault": Sinner("LCB Sinner Meursault", 184, 2, 3, 38, 26, [0, 50, -25], [50, 20],
                                   [Skill("Un, Deux", Sin.SLOTH, 2, 2, 4, 2, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.TREMOR)]]),
                                    Skill("Nailing Fist", Sin.PRIDE, 2, 5, 8, 1, [Effect(EffectTrigger.ON_USE, EffectDetails.GAIN_STATUS_NEXT_TURN, 3, status=StatusType.DEFENSE_LEVEL_UP)],
                                                                                 [[Effect(EffectTrigger.ON_HIT, EffectDetails.BURST_TREMOR, 1)]]),
                                    Skill("Des Coups", Sin.GLOOM, 2, 4, 1, 4, [Effect(EffectTrigger.ON_USE, EffectDetails.GAIN_STATUS_NEXT_TURN, 3, status=StatusType.PROTECTION)],
                                          [[], [], [], [Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT, 2, status=StatusType.TREMOR)]])]),
    "LCB Sinner Ishmael": Sinner("LCB Sinner Ishmael", 159, 5, 8, 33, 31, [50, 0, -25], [60, 30],
                                 [Skill("Loggerhead", Sin.WRATH, 2, 3, 7, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT, 1, status=StatusType.TREMOR)]]),
                                  Skill("Slide", Sin.GLUTTONY, 2, 5, 8, 1, [Effect(EffectTrigger.ClASH_WIN, EffectDetails.INFLICT_STATUS, 3, status=StatusType.DEFENSE_POWER_DOWN)], []),
                                  Skill("Guard", Sin.GLOOM, 2, 7, 12, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.BURST_TREMOR, 1)],
                                                                              [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BLUNT_FRAGILITY)]])]),
    "LCB Sinner Hong Lu": Sinner("LCB Sinner Hong Lu", 134, 3, 6, 28, 36, [50, 0, -25], [70, 40, 20],
                                 [Skill("Downward Cleave", Sin.PRIDE, 2, 3, 7, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.SINKING)]]),
                                  Skill("Dual Strike", Sin.SLOTH, 0, 4, 4, 2, [Effect(EffectTrigger.ON_USE, EffectDetails.COIN_POWER, 1, condition=[Condition(EffectCondition.TOOK_NO_DAMAGE_LAST_TURN)])],
                                        [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.SINKING)],
                                         [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.RUPTURE)]]),
                                  Skill("Whirlwind", Sin.LUST, 2, 5, 4, 2, [Effect(EffectTrigger.ON_USE, EffectDetails.COIN_POWER, 2, condition=[Condition(EffectCondition.TOOK_NO_DAMAGE_LAST_TURN)])],
                                        [[], [Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.ATTACK_POWER_DOWN)]])]),
    "LCB Sinner Heathcliff": Sinner("LCB Sinner Heathcliff", 159, 2, 5, 31, 33, [50, 0, -25], [65, 35, 15],
                                    [Skill("Bat Bash", Sin.ENVY, 2, 3, 7, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 3, status=StatusType.TREMOR)]]),
                                     Skill("Smackdown", Sin.WRATH, 2, 4, 4, 2, [Effect(EffectTrigger.ON_USE, EffectDetails.GAIN_STATUS_NEXT_TURN, 1, status=StatusType.ATTACK_POWER_UP),
                                                                     Effect(EffectTrigger.ON_USE, EffectDetails.GAIN_STATUS_NEXT_TURN, 1, status=StatusType.DAMAGE_UP)], []),
                                     Skill("Upheaval", Sin.LUST, 2, 4, 6, 2, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.RAISE_NEXT_COIN, 2)],
                                                                                  [Effect(EffectTrigger.ON_HIT, EffectDetails.BURST_TREMOR, 1)]])]),
    "LCB Sinner Gregor": Sinner("LCB Sinner Gregor", 146, 3, 7, 33, 33, [-25, 0, 50], [70, 30],
                                [Skill("Swipe", Sin.GLOOM, 0, 3, 7, 1, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 4, status=StatusType.RUPTURE)]]),
                                 Skill("Jag", Sin.GLUTTONY, 1, 4, 10, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT, 1, status=StatusType.RUPTURE),
                                                                 Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.PIERCE_FRAGILITY)]]),
                                 Skill("Chop Up", Sin.SLOTH, 1, 5, 4, 2, [], [[Effect(EffectTrigger.BEFORE_HIT, EffectDetails.COIN_DMG_MULT, 10, condition=[Condition(EffectCondition.TARGET_HAS_STATUS_OF_AMOUNT, condition_status=StatusType.RUPTURE, condition_amount=1)] )],
                                                                   [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.COIN_DMG_MULT, 10, condition=[Condition(EffectCondition.TARGET_HAS_STATUS_OF_AMOUNT, condition_status=StatusType.RUPTURE, condition_amount=1)]),
                                                                    Effect(EffectTrigger.HEADS_HIT, EffectDetails.HEAL_FOR_DAMAGE, 30)]])]),
    "LCB Sinner Faust": Sinner("LCB Sinner Faust", 171, 2, 4, 35, 28, [50, -25, 0], [60, 30, 15],
                               [Skill("Downward Slash", Sin.PRIDE, 2, 3, 7, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.PARALYZE)]]),
                                Skill("Upward Slash", Sin.SLOTH, 2, 4, 4, 2, [], [[], [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS_NEXT_TURN, 2, status=StatusType.OFFENSE_LEVEL_DOWN)]]),
                                Skill("Drilling Stab", Sin.GLUTTONY, 1, 6, 2, 2, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS_NEXT_TURN, 1, status=StatusType.ATTACK_POWER_DOWN)],
                                                                        [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS_NEXT_TURN, 1, status=StatusType.ATTACK_POWER_DOWN)]])]),
    "LCB Sinner Don Quixote": Sinner("LCB Sinner Don Quixote", 134, 3, 6, 27, 36, [0, -25, 50], [70, 40, 20],
                                     [Skill("Joust", Sin.LUST, 1, 3, 7, 1, [Effect(EffectTrigger.ClASH_WIN, EffectDetails.GAIN_STATUS_NEXT_TURN, 2, status=StatusType.HASTE)], []),
                                      Skill("Galloping Tilt", Sin.ENVY, 1, 4, 10, 1, [Effect(EffectTrigger.ClASH_WIN, EffectDetails.GAIN_STATUS_NEXT_TURN, 2, status=StatusType.ATTACK_POWER_UP)], []),
                                      Skill("For Justice!", Sin.GLUTTONY, 1, 3, 3, 3, [Effect(EffectTrigger.ON_USE, EffectDetails.COIN_POWER, 2, condition=[Condition(EffectCondition.SPEED_AT_LEAST_X, condition_amount=10)])], [])]),
    "Seven Section 6 Yi Sang": Sinner("Seven Section 6 Yi Sang", 164, 5, 8, 34, 32, [0, -25, 50], [60, 30],
                                     [Skill("Flèche", Sin.GLOOM, 1, 4, 6, 1, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.RUPTURE)]]),
                                      Skill("Riposte", Sin.GLUTTONY, 1, 5, 2, 2, [], [[], [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS_NEXT_TURN, 1, status=StatusType.FRAGILE)]]),
                                      Skill("Moulinet", Sin.SLOTH, 2, 5, 3, 3, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.BOOST_STATUS_OF_FUTURE_COIN, 1)],
                                                                                    [Effect(EffectTrigger.ON_HIT, EffectDetails.BOOST_STATUS_OF_FUTURE_COIN, 1)],
                                                                                    [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS_NEXT_TURN, 1, status=StatusType.PIERCE_FRAGILITY)]])]),
    "Zwei Section 6 Sinclair": Sinner("Zwei Section 6 Sinclair", 176, 2, 4, 37, 29, [50, 0, -25], [55, 20],
                                     [Skill("Baton", Sin.GLOOM, 1, 4, 6, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.TREMOR)]]),
                                      Skill("Suppress", Sin.WRATH, 1, 6, 1, 2, [], [[], [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 6, status=StatusType.TREMOR),
                                                                                         Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS_NEXT_TURN, 2, status=StatusType.DAMAGE_DOWN)]]),
                                      Skill("Strong Strike", Sin.SLOTH, 1, 7, 13, 1, [Effect(EffectTrigger.ON_USE, EffectDetails.GIVE_STATUS_TO_LOWEST_ALLY, 1, status=StatusType.PROTECTION)],
                                            [[Effect(EffectTrigger.ON_HIT, EffectDetails.BURST_TREMOR, 1)],
                                             [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.BLUNT_FRAGILITY)]])]),
    "Jefe de Los Mariachis Sinclair": Sinner("Jefe de Los Mariachis Sinclair", 190, 2, 3, 40, 27, [50, 0, -25], [50],
                                     [Skill("Baile y Rola", Sin.SLOTH, 2, 4, 2, 2, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 4, status=StatusType.SINKING)]]),
                                      Skill("Danza de Pasión", Sin.ENVY, 2, 5, 1, 3, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS, 2, status=StatusType.POISE),
                                                                                           Effect(EffectTrigger.HEADS_HIT, EffectDetails.GAIN_STATUS_COUNT, 1, status=StatusType.POISE)],
                                                                                          [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.SINKING),
                                                                                           Effect(EffectTrigger.HEADS_HIT, EffectDetails.APPLY_STATUS_COUNT, 1, status=StatusType.SINKING)],
                                                                                          [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.SINKING)]]),
                                      Skill("Piñata Party", Sin.GLOOM, 2, 8, 11, 1, [Effect(EffectTrigger.ON_USE, EffectDetails.NEG_SP_TO_CRIT, 0)],
                                            [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.LOWER_SELF_STAGGER_BY_DAMAGE, 50)]])]),
    "Seven Section 6 Ryoshu": Sinner("Seven Section 6 Ryoshu", 126, 3, 7, 27, 40, [-25, 0, 50], [70, 40, 20],
                               [Skill("Slash", Sin.SLOTH, 2, 4, 6, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.RUPTURE)]]),
                                Skill("Upper Slash", Sin.PRIDE, 1, 4, 12, 1, [Effect(EffectTrigger.ON_USE, EffectDetails.SKILL_POWER, 2, condition=[Condition(EffectCondition.TARGET_HAS_STATUS_OF_AMOUNT, condition_amount=1, condition_status=StatusType.SLASH_FRAGILITY)]),
                                                                              Effect(EffectTrigger.ClASH_WIN, EffectDetails.GAIN_STATUS_NEXT_TURN, 1, status=StatusType.ATTACK_POWER_UP)],
                                                                            [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.DEFENSE_LEVEL_DOWN)]]),
                                Skill("Swash", Sin.GLUTTONY, 1, 4, 5, 3, [Effect(EffectTrigger.ClASH_WIN, EffectDetails.BOOST_STATUS_OF_FUTURE_COIN, 2)],
                                                                         [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS_NEXT_TURN, 3, status=StatusType.SLASH_FRAGILITY)]])]),
    "N Corp. Mittelhammer Rodion": Sinner("N Corp. Mittelhammer Rodion", 138, 3, 7, 29, 37, [-25, 0, 50], [70, 40, 20],
                                     [Skill("Devoted Hammering", Sin.PRIDE, 1, 3, 4, 2, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BLEED)],
                                                                                             [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BLEED)]]),
                                      Skill("Zealous Purge", Sin.LUST, 2, 6, 2, 2, [Effect(EffectTrigger.ClASH_WIN, EffectDetails.GAIN_STATUS_NEXT_TURN, 1, status=StatusType.FANATIC)],
                                                                                   [[Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT_NEXT_TURN, 1, status=StatusType.NAILS)],
                                                                                    [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS_NEXT_TURN, 1, status=StatusType.PARALYZE)]]),
                                      Skill("Ironclad Retribution", Sin.WRATH, 2, 4, 2, 4, [Effect(EffectTrigger.ON_USE, EffectDetails.RAISE_ATTACK_DAMAGE_MULT, 15, condition=[Condition(EffectCondition.SELF_HAS_STATUS_OF_AMOUNT, condition_amount=1, condition_status=StatusType.FANATIC)])],
                                                                                           [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BLEED)],
                                                                                            [Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BLEED)]])]),
    "LCCB Assistant Manager Rodion": Sinner("LCCB Assistant Manager Rodion", 126, 3, 7, 27, 40, [0, 50, -25], [70, 40, 20],
                                 [Skill("Bludgeon", Sin.PRIDE, 2, 4, 6, 1, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 3, status=StatusType.PARALYZE)]]),
                                  Skill("Thrust", Sin.GLUTTONY, 2, 6, 1, 2, [], [[], [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 4, status=StatusType.DEFENSE_POWER_DOWN)]]),
                                  Skill("Suppress", Sin.ENVY, 2, 7, 2, 2, [Effect(EffectTrigger.ON_USE, EffectDetails.COIN_POWER, 2, condition=[Condition(EffectCondition.TOOK_NO_DAMAGE_THIS_TURN)])],
                                                                          [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 4, status=StatusType.DEFENSE_POWER_DOWN),
                                                                            Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.DEFENSE_POWER_DOWN)],
                                                                           [Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 3, status=StatusType.PARALYZE)]])]),
    "G Corp. Head Manager Outis": Sinner("G Corp. Head Manager Outis", 151, 4, 8, 37, 29, [0, -25, 50], [65, 35],
                                 [Skill("Order", Sin.SLOTH, 1, 4, 6, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.GIVE_STATUS_TO_SLOWEST_ALLY, 2, status=StatusType.PROTECTION)]]),
                                  Skill("Onslaught Command", Sin.GLUTTONY, 2, 5, 10, 1, [Effect(EffectTrigger.ON_USE, EffectDetails.GIVE_STATUS_TO_SLOWEST_ALLY, 1, status=StatusType.ATTACK_POWER_UP)],
                                                                                        [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.GIVE_STATUS_TO_SLOWEST_ALLY, 2, status=StatusType.DAMAGE_UP)]]),
                                  Skill("Focus", Sin.GLOOM, 2, 6, 16, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 5, status=StatusType.SINKING),
                                                                               Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.ATTACK_POWER_DOWN)]])]),
    "Blade Lineage Cutthroat Outis": Sinner("Blade Lineage Cutthroat Outis", 164, 2, 5, 32, 34, [-25, 50, 0], [65, 35, 15],
                                 [Skill("Draw of the Sword", Sin.WRATH, 0, 4, 6, 1, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.GAIN_STATUS, 4, status=StatusType.POISE)]]),
                                  Skill("Acupuncture", Sin.LUST, 1, 5, 4, 2, [Effect(EffectTrigger.ClASH_WIN, EffectDetails.GAIN_STATUS_COUNT, 1, status=StatusType.POISE)],
                                        [[], [Effect(EffectTrigger.HEADS_HIT, EffectDetails.GAIN_STATUS, 2, status=StatusType.SLASH_DAMAGE_UP)]]),
                                  Skill("Decisive Dive", Sin.PRIDE, 0, 6, 4, 2, [Effect(EffectTrigger.ON_USE, EffectDetails.SKILL_POWER, 2, condition=[Condition(EffectCondition.TARGET_BELOW_HP, condition_amount=25)])],
                                        [[], [Effect(EffectTrigger.ON_HIT, EffectDetails.RAISE_STAGGER_BY_DAMAGE, 20, condition=[Condition(EffectCondition.ON_CRIT)])]])]),
    "Liu Section 6 Meursault": Sinner("Liu Section 6 Meursault", 164, 2, 5, 32, 34, [0, 50, -25], [65, 35, 15],
                                 [Skill("Assault", Sin.LUST, 2, 3, 4, 2, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BURN)],
                                                                              [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BURN)]]),
                                  Skill("Stalwart Stance", Sin.SLOTH, 2, 6, 2, 2, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.BURN),
                                                                                        Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_TO_RANDOM_ENEMIES, 2, other=2, status=StatusType.BURN, condition=[Condition(EffectCondition.TARGET_HAS_STATUS_OF_AMOUNT, condition_amount=6, condition_status=StatusType.BURN)])],
                                                                                       [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BURN)]]),
                                  Skill("Perfected Death Fist", Sin.WRATH, 1, 5, 3, 3, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 3, status=StatusType.BURN)], [],
                                                                                            [Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT, 3, status=StatusType.BURN),
                                                                                             Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_TO_RANDOM_ENEMIES, 2, other=2, status=StatusType.BURN, condition=[Condition(EffectCondition.TARGET_HAS_STATUS_OF_AMOUNT, condition_amount=6, condition_status=StatusType.BURN)])]])]),
    "Shi Section 5 Ishmael": Sinner("Shi Section 5 Ishmael", 166, 2, 5, 32, 34, [-25, 50, 0], [80, 60],
                                 [Skill("Flying Sword", Sin.ENVY, 1, 5, 3, 2, [Effect(EffectTrigger.ON_USE, EffectDetails.APPLY_STATUS_COUNT, 1, status=StatusType.POISE, condition=[Condition(EffectCondition.SELF_BELOW_HP, condition_amount=50)])],
                                        [[], [Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS, 2, status=StatusType.POISE)]]),
                                  Skill("Flashing Strike", Sin.LUST, 0, 5, 4, 2, [Effect(EffectTrigger.ON_USE, EffectDetails.REPEAT_COIN, 1, condition=[Condition(EffectCondition.SELF_BELOW_HP, condition_amount=50)]),
                                                                                  Effect(EffectTrigger.ON_USE, EffectDetails.REPEAT_COIN, 2, condition=[Condition(EffectCondition.SELF_BELOW_HP, condition_amount=50)])],
                                        [[Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_COUNT, 1, status=StatusType.POISE)],
                                         [Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_COUNT, 1, status=StatusType.POISE)]]),
                                  Skill("Catch Breath", Sin.WRATH, 0, 6, 4, 2, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS, 2, status=StatusType.POISE)],
                                                                                    [Effect(EffectTrigger.ON_HIT, EffectDetails.HEAL_FOR_DAMAGE, 100, condition=[Condition(EffectCondition.ON_CRIT), Condition(EffectCondition.SELF_BELOW_HP, condition_amount=25)])]])]),
    "LCCB Assistant Manager Ishmael": Sinner("LCCB Assistant Manager Ishmael", 164, 2, 6, 37, 29, [0, 50, -25], [55, 20],
                                 [Skill("Shove", Sin.GLUTTONY, 2, 4, 6, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 3, status=StatusType.PARALYZE)]]),
                                  Skill("Quake Rounds", Sin.GLOOM, 2, 4, 3, 3, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.ATTACK_POWER_DOWN)],
                                                                                    [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.SPEND_AMMO, 1),
                                                                                     Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 8, status=StatusType.TREMOR),
                                                                                     Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT, 2, status=StatusType.TREMOR)],
                                                                                    [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.SPEND_AMMO, 1),
                                                                                     Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 4, status=StatusType.TREMOR),
                                                                                     Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT, 2, status=StatusType.TREMOR)],
                                                                                    ]),
                                  Skill("Suppress", Sin.PRIDE, 2, 4, 2, 4, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.BURST_TREMOR, 1)],
                                                                                    [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.SPEND_AMMO, 1),
                                                                                     Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 4, status=StatusType.RUPTURE),
                                                                                     Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT, 2, status=StatusType.RUPTURE)],
                                                                                    [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.SPEND_AMMO, 1),
                                                                                     Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 4, status=StatusType.RUPTURE),
                                                                                     Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT, 2, status=StatusType.RUPTURE)],
                                                                                    [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.SPEND_AMMO, 1),
                                                                                     Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 5, status=StatusType.FRAGILE)]
                                                                                    ])]),
    "Kurokumo Wakashu Hong Lu": Sinner("Kurokumo Wakashu Hong Lu", 151, 3, 7, 34, 32, [-25, 0, 50], [65, 35, 15],
                                 [Skill("Cleave", Sin.LUST, 0, 4, 6, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.BLEED)]]),
                                  Skill("Cloud Cutter", Sin.PRIDE, 0, 5, 4, 2, [Effect(EffectTrigger.BEFORE_ATTACK, EffectDetails.REPEAT_COIN, 1, condition=[Condition(EffectCondition.TARGET_HAS_LESS_STATUS_OF_AMOUNT, condition_amount=4, condition_status=StatusType.BLEED)]),
                                                                                Effect(EffectTrigger.BEFORE_ATTACK, EffectDetails.REPEAT_COIN, 2, condition=[Condition(EffectCondition.TARGET_HAS_LESS_STATUS_OF_AMOUNT, condition_amount=4, condition_status=StatusType.BLEED)])],
                                        [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BLEED)],
                                         [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.BLEED)]]),
                                  Skill("Cloudburst", Sin.SLOTH, 0, 6, 2, 3, [Effect(EffectTrigger.COMBAT_START, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BLEED), Effect(EffectTrigger.COMBAT_START, EffectDetails.INFLICT_STATUS, 1, status=StatusType.PARALYZE)],
                                        [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.BLEED)],
                                         [Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.BLEED)],
                                         [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 5, status=StatusType.PARALYZE)]])]),
    "Shi Section 5 Heathcliff": Sinner("Shi Section 5 Heathcliff", 164, 2, 5, 32, 34, [-25, 50, 0], [80, 60],
                                 [Skill("Extreme Edge", Sin.LUST, 0, 4, 6, 1, [Effect(EffectTrigger.ON_USE, EffectDetails.SKILL_POWER, 2, condition=[Condition(EffectCondition.SELF_BELOW_HP, condition_amount=25)])], []),
                                  Skill("Flying Sword", Sin.WRATH, 1, 5, 10, 1, [Effect(EffectTrigger.ON_USE, EffectDetails.SKILL_POWER, 2, condition=[Condition(EffectCondition.SELF_BELOW_HP, condition_amount=25)])], []),
                                  Skill("Flashing Strike", Sin.ENVY, 0, 5, 6, 2, [Effect(EffectTrigger.ON_USE, EffectDetails.SKILL_POWER, 2, condition=[Condition(EffectCondition.SELF_BELOW_HP, condition_amount=25)])],
                                        [[Effect(EffectTrigger.BEFORE_HIT, EffectDetails.LOSE_HP, 5), Effect(EffectTrigger.BEFORE_HIT, EffectDetails.COIN_DMG_MULT, 50)],
                                         [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.LOSE_HP, 5), Effect(EffectTrigger.BEFORE_HIT, EffectDetails.COIN_DMG_MULT, 50)]])]),
    "N Corp. Kleinhammer Heathcliff": Sinner("N Corp. Kleinhammer Heathcliff", 154, 3, 7, 35, 33, [-25, 0, 50], [65, 35, 15],
                                 [Skill("Gawky Nailing", Sin.GLOOM, 1, 3, 4, 2, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.APPLY_STATUS_COUNT_NEXT_TURN, 1, status=StatusType.NAILS),
                                                                                      Effect(EffectTrigger.TAILS_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BLEED)],
                                                                                     [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BLEED)]]),
                                  Skill("Puri...fy!", Sin.ENVY, 2, 6, 8, 1, [Effect(EffectTrigger.ClASH_WIN, EffectDetails.HEAL_SP, 5)],
                                        [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS_NEXT_TURN, 2, status=StatusType.PLUS_COIN_DROP)]]),
                                  Skill("Infirm Retribution", Sin.SLOTH, 2, 4, 4, 3, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.DEAL_PERCENT_BONUS_DAMAGE, 10)],
                                                                                          [Effect(EffectTrigger.HEADS_HIT, EffectDetails.DEAL_PERCENT_BONUS_DAMAGE, 10)],
                                                                                          [Effect(EffectTrigger.HEADS_HIT, EffectDetails.DEAL_PERCENT_BONUS_DAMAGE, 10)]])]),
    "Liu Section 6 Gregor": Sinner("Liu Section 6 Gregor", 126, 3, 7, 27, 40, [0, 50, -25], [60, 30],
                                 [Skill("Single-point Stab", Sin.WRATH, 2, 4, 2, 2, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BURN)],
                                                                               [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BURN)]]),
                                  Skill("Rush Down", Sin.LUST, 2, 5, 1, 3, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BURN)],
                                                                                    [Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BURN)],
                                                                                    [Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_NEXT_TURN, 1, status=StatusType.OFFENSE_LEVEL_UP, condition=[Condition(EffectCondition.TARGET_HAS_STATUS_OF_AMOUNT, condition_amount=6, condition_status=StatusType.BURN)])]]),
                                  Skill("Perfected Palm Strike", Sin.SLOTH, 2, 4, 2, 4, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BURN)],
                                                                                             [Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BURN)],
                                                                                             [Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BURN)],
                                                                                             [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 3, status=StatusType.BURN)]])]),
    "W Corp. Cleanup Agent Faust": Sinner("W Corp. Cleanup Agent Faust", 176, 2, 4, 37, 28, [0, -25, 50], [60, 30],
                                 [Skill("Energy Cycle", Sin.ENVY, 2, 4, 6, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_COUNT, 2, status=StatusType.CHARGE)]]),
                                  Skill("Leap", Sin.GLOOM, 2, 5, 4, 2, [], [[], [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 4, status=StatusType.BIND, condition=[Condition(EffectCondition.SPEND_CHARGE, condition_amount=3)])]]),
                                  Skill("Overcharge", Sin.WRATH, 2, 6, 2, 3, [], [[], [], [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS_NEXT_TURN, 2, status=StatusType.ATTACK_POWER_DOWN, condition=[Condition(EffectCondition.SPEND_CHARGE, condition_amount=5)]),
                                                                                           Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 3, status=StatusType.PARALYZE)]])]),
    "Lobotomy Corp. Remnant Faust": Sinner("Lobotomy Corp. Remnant Faust", 138, 3, 6, 29, 37, [-25, 0, 50], [70, 40, 20],
                                 [Skill("Sole Strike", Sin.LUST, 0, 3, 6, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.RUPTURE)]]),
                                  Skill("Deep Cuts", Sin.GLOOM, 1, 4, 3, 3, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_NEXT_TURN, 1, status=StatusType.POISE)],
                                                                                 [Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_NEXT_TURN, 1, status=StatusType.POISE)],
                                                                                 [Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_NEXT_TURN, 4, status=StatusType.HASTE)]]),
                                  Skill("Opportunistic Slash", Sin.ENVY, 0, 4, 8, 2, [Effect(EffectTrigger.ON_USE, EffectDetails.COIN_POWER, 3, condition=[Condition(EffectCondition.TOOK_NO_DAMAGE_LAST_TURN)])],
                                        [[], [Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 5, status=StatusType.RUPTURE)]])]),
    "Shi Section 5 Don Quixote": Sinner("Shi Section 5 Don Quixote", 138, 3, 6, 29, 37, [-25, 50, 0], [80, 60],
                                 [Skill("Catch Breath", Sin.WRATH, 0, 4, 6, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_NEXT_TURN, 2, status=StatusType.POISE)]]),
                                  Skill("Dual Strike", Sin.ENVY, 0, 4, 6, 2, [Effect(EffectTrigger.ON_USE, EffectDetails.GAIN_STATUS_NEXT_TURN, 2, status=StatusType.HASTE, condition=[Condition(EffectCondition.SELF_BELOW_HP, condition_amount=50)])],
                                        [[Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_NEXT_TURN, 1, status=StatusType.POISE)],
                                         [Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_NEXT_TURN, 2, status=StatusType.HASTE)]]),
                                  Skill("Overbreathe", Sin.LUST, 0, 4, 21, 1, [Effect(EffectTrigger.ON_USE, EffectDetails.SKILL_POWER, 3, condition=[Condition(EffectCondition.SPEED_AT_LEAST_X, condition_amount=10)])], [])]),
    "Blade Lineage Salsu Yi Sang": Sinner("Blade Lineage Salsu Yi Sang", 132, 3, 7, 28, 41, [-25, 50, 0], [70, 40, 20],
                                 [Skill("Striker's Stance", Sin.PRIDE, 0, 5, 6, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_NEXT_TURN, 3, status=StatusType.POISE)]]),
                                  Skill("Heel Turn", Sin.WRATH, 0, 7, 1, 2, [Effect(EffectTrigger.ClASH_WIN, EffectDetails.GAIN_STATUS_COUNT_NEXT_TURN, 2, status=StatusType.POISE)], []),
                                  Skill("Flank Thrust", Sin.ENVY, 0, 8, 1, 3, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.GAIN_STATUS_NEXT_TURN, 2, status=StatusType.POISE)],[],
                                                                                   [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.COIN_DMG_MULT, 50, condition=[Condition(EffectCondition.ON_CRIT)])]])]),
    "Blade Lineage Salsu Sinclair": Sinner("Blade Lineage Salsu Sinclair", 172, 2, 5, 33, 35, [-25, 50, 0], [60, 30],
                                 [Skill("Slice then Stab", Sin.GLUTTONY, 1, 5, 1, 2, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT, 2, status=StatusType.POISE)]]),
                                  Skill("Slash Series", Sin.WRATH, 0, 6, 1, 3, [Effect(EffectTrigger.ClASH_LOSE, EffectDetails.GAIN_STATUS_NEXT_TURN, 2, status=StatusType.ATTACK_POWER_UP)],
                                        [[Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS, 2, status=StatusType.POISE)],
                                         [Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS, 1, status=StatusType.POISE)],
                                         [Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS, 1, status=StatusType.POISE)]]),
                                  Skill("To Claim Their Bones", Sin.PRIDE, 0, 8, 14, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 5, status=StatusType.PARALYZE),
                                                                                              Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 3, status=StatusType.BLEED)]])]),
    "Kurokumo Wakashu Ryoshu": Sinner("Kurokumo Wakashu Ryoshu", 146, 3, 6, 30, 38, [50, -25, 0], [70, 40, 20],
                                 [Skill("Focus Strike", Sin.GLUTTONY, 1, 5, 6, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 3, status=StatusType.PARALYZE)]]),
                                  Skill("Clean Up", Sin.PRIDE, 1, 5, 5, 2, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 3, status=StatusType.PARALYZE)],
                                                                                [Effect(EffectTrigger.HEADS_HIT, EffectDetails.APPLY_STATUS_COUNT, 1, status=StatusType.BLEED),
                                                                                 Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.DAMAGE_DOWN)]]),
                                  Skill("Lenticular Swirl", Sin.LUST, 1, 8, 4, 2, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.BLEED)],
                                                                                       [Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT, 3, status=StatusType.BLEED),
                                                                                        Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 3, status=StatusType.OFFENSE_LEVEL_DOWN)]])]),
    "Kurokumo Henchwoman Rodion": Sinner("Kurokumo Henchwoman Rodion", 172, 2, 5, 33, 35, [-25, 0, 50], [60, 30],
                                 [Skill("Sharpened Blade", Sin.GLOOM, 0, 5, 6, 1, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.GAIN_STATUS, 4, status=StatusType.POISE)]]),
                                  Skill("Scattering Slash", Sin.LUST, 0, 6, 3, 2, [Effect(EffectTrigger.ON_USE, EffectDetails.GAIN_STATUS_COUNT, 1, status=StatusType.POISE)],
                                        [[Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS, 2, status=StatusType.POISE),
                                          Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.BLEED)],
                                         [Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS, 3, status=StatusType.POISE),
                                          Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 3, status=StatusType.BLEED)]]),
                                  Skill("Sky-clearing Cut", Sin.PRIDE, 0, 7, 16, 1, [Effect(EffectTrigger.ON_USE, EffectDetails.DOUBLE_CRIT_CHANCE, 1, condition=[Condition(EffectCondition.TARGET_HAS_STATUS_OF_AMOUNT, condition_amount=6)])],
                                        [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 10, status=StatusType.BLEED, condition=[Condition(EffectCondition.ON_CRIT)])]])]),
    "W Corp. Cleanup Agent Meursault": Sinner("W Corp. Cleanup Agent Meursault", 158, 4, 8, 38, 30, [0, -25, 50], [60, 30],
                                 [Skill("Rip", Sin.ENVY, 0, 5, 6, 1, [Effect(EffectTrigger.ON_USE, EffectDetails.GAIN_STATUS, 2, status=StatusType.SLASH_PROTECTION)],
                                        [[Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_COUNT, 3, status=StatusType.CHARGE)]]),
                                  Skill("Energy Cycle", Sin.GLOOM, 0, 5, 2, 3, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.RUPTURE)],
                                                                                    [Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.RUPTURE)],
                                                                                    [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 3, status=StatusType.RUPTURE),
                                                                                     Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.SLASH_FRAGILITY, condition=[Condition(EffectCondition.SPEND_CHARGE, condition_amount=3)])]]),
                                  Skill("Energy Current", Sin.PRIDE, 0, 5, 1, 4, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.DEFENSE_LEVEL_DOWN, condition=[Condition(EffectCondition.SPEND_CHARGE, condition_amount=2)])],
                                                                                      [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.DEFENSE_LEVEL_DOWN, condition=[Condition(EffectCondition.SPEND_CHARGE, condition_amount=2)])],
                                                                                      [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.DEFENSE_LEVEL_DOWN, condition=[Condition(EffectCondition.SPEND_CHARGE, condition_amount=2)])],
                                                                                      [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.DEFENSE_LEVEL_DOWN, condition=[Condition(EffectCondition.SPEND_CHARGE, condition_amount=2)])]])]),
    "N Corp. Grosẞhammer Meursault": Sinner("N Corp. Grosẞhammer Meursault", 198, 3, 5, 42, 32, [0, -25, 50], [50],
                                 [Skill("Drive", Sin.SLOTH, 1, 5, 1, 2, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.LOWER_SELF_STAGGER_BY_DAMAGE, 60)],
                                                                             [Effect(EffectTrigger.ON_HIT, EffectDetails.LOWER_SELF_STAGGER_BY_DAMAGE, 60)]]),
                                  Skill("You Are Cleansed of Sin", Sin.WRATH, 2, 6, 3, 2, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT, 3, status=StatusType.NAILS)],
                                                                                               [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS_NEXT_TURN, 3, status=StatusType.BIND),
                                                                                                Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS_NEXT_TURN, 2, status=StatusType.BIND, condition=[Condition(EffectCondition.TARGET_HAS_STATUS_OF_COUNT, condition_amount=5, condition_status=StatusType.NAILS)]),
                                                                                                Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS_NEXT_TURN, 1, status=StatusType.ATTACK_POWER_DOWN, condition=[Condition(EffectCondition.TARGET_HAS_STATUS_OF_COUNT, condition_amount=5, condition_status=StatusType.NAILS)])]]),
                                  Skill("Annihilate Heretics", Sin.PRIDE, 1, 8, 3, 2, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT_NEXT_TURN, 2, status=StatusType.NAILS)],
                                                                                           [Effect(EffectTrigger.ON_HIT, EffectDetails.HEAL_FOR_DAMAGE, 50)]])]),
    "R Corp. 4th Pack Reindeer Ishmael": Sinner("R Corp. 4th Pack Reindeer Ishmael", 157, 3, 7, 35, 32, [50, 0, -25], [70, 30],
                                                [Skill("Mind Strike", Sin.GLOOM, 2, 3, 5, 2, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.SINKING),
                                                                                Effect(EffectTrigger.HEADS_HIT, EffectDetails.GAIN_STATUS_COUNT, 2, status=StatusType.CHARGE)],
                                                                               [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.SINKING),
                                                                                Effect(EffectTrigger.HEADS_HIT, EffectDetails.GAIN_STATUS_COUNT, 2, status=StatusType.CHARGE)]]),
                                                 Skill("Flaying Surge", Sin.ENVY, 2, 6, 10, 1, [Effect(EffectTrigger.ON_USE, EffectDetails.GAIN_STATUS_COUNT, 5, status=StatusType.CHARGE)],
                                        [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.APPLY_STATUS_COUNT, 3, status=StatusType.SINKING)]]),
                                                 Skill("Mind Whip", Sin.WRATH, 2, 2, 5, 4, [Effect(EffectTrigger.COMBAT_START, EffectDetails.TARGET_RANDOM, 0, condition=[Condition(EffectCondition.SELF_HAS_STATUS_BELOW_COUNT, condition_amount=10, condition_status=StatusType.CHARGE)]),
                                                                                             Effect(EffectTrigger.COMBAT_START, EffectDetails.REMOVE_STATUS, 0, status=StatusType.CHARGE)], # TODO: Mind strike de-priotization in team battles
                                                       [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.SINKING)],
                                                        [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.SINKING)],
                                                        [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.SINKING)],
                                                        [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.SINKING)]])]),
     "Tingtang Gangleader Hong Lu": Sinner("Tingtang Gangleader Hong Lu", 154, 3, 6, 35, 38, [-25, 0, 50], [70, 40, 20],
                                 [Skill("Throat Slit", Sin.ENVY, 0, 5, 6, 1, [], [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 4, status=StatusType.BLEED)]]),
                                  Skill("Shank", Sin.LUST, 1, 3, 5, 3, [], [[Effect(EffectTrigger.BEFORE_DAMAGE, EffectDetails.ADDED_DAMAGE, 3)],
                                                                            [Effect(EffectTrigger.BEFORE_DAMAGE, EffectDetails.ADDED_DAMAGE, 3)],
                                                                            [Effect(EffectTrigger.ON_HIT, EffectDetails.REPEAT_COIN, 3, condition=[Condition(EffectCondition.ON_COIN, condition_amount=3), Condition(EffectCondition.TARGET_BELOW_HP, condition_amount=25), Condition(EffectCondition.GOT_HEADS)]),
                                                                             Effect(EffectTrigger.BEFORE_DAMAGE, EffectDetails.COIN_DMG_MULT, 50),
                                                                             Effect(EffectTrigger.BEFORE_DAMAGE, EffectDetails.COIN_DMG_MULT, 50, condition=[Condition(EffectCondition.ON_COIN, condition_amount=4)])]]),
                                  Skill("Mutilate", Sin.GLUTTONY, 0, 5, 25, 1, [], [[Effect(EffectTrigger.BEFORE_DAMAGE, EffectDetails.ADDED_DAMAGE, 7)]])]),  # TODO: Handle On Kill Effect
    "R Corp. 4th Pack Rabbit Heathcliff": Sinner("R Corp. 4th Pack Rabbit Heathcliff", 134, 3, 7, 28, 41, [0, -25, 50], [70, 40, 20],
                                 [Skill("Graze the Grass", Sin.WRATH, 1, 4, 2, 3, [], [[Effect(EffectTrigger.BEFORE_HIT, EffectDetails.SPEND_AMMO, 1)],
                                                                                       [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.SPEND_AMMO, 1)],
                                                                                       [Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_COUNT, 3, status=StatusType.CHARGE)]]),
                                  Skill("Concentrated Fire", Sin.GLUTTONY, 1, 4, 2, 4, [Effect(EffectTrigger.ON_USE, EffectDetails.COIN_POWER, 1, condition=[Condition(EffectCondition.SPEED_AT_LEAST_X, condition_amount=6)])],
                                        [[Effect(EffectTrigger.BEFORE_HIT, EffectDetails.SPEND_AMMO, 1),
                                          Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BLEED)],
                                         [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.SPEND_AMMO, 1),
                                          Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BLEED)],
                                         [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.SPEND_AMMO, 1),
                                          Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.BLEED)]]),
                                  Skill("Quick Suppression", Sin.ENVY, 1, 3, 2, 5, [Effect(EffectTrigger.ON_USE, EffectDetails.COIN_POWER, 2, condition=[Condition(EffectCondition.SPEED_AT_LEAST_X, condition_amount=6)])],
                                        [[Effect(EffectTrigger.BEFORE_HIT, EffectDetails.SPEND_AMMO, 1),
                                          Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.FRAGILE)],
                                         [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.SPEND_AMMO, 1),
                                          Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.FRAGILE)],
                                         [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.RUPTURE)],
                                         [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.RUPTURE)],
                                         [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 3, status=StatusType.RUPTURE)]])]),
    "G Corp. Manager Corporal Gregor": Sinner("G Corp. Manager Corporal Gregor", 134, 3, 7, 28, 41, [0, -25, 50], [70, 40, 20],
                                 [Skill("Hack", Sin.GLUTTONY, 0, 4, 3, 2, [Effect(EffectTrigger.ClASH_WIN, EffectDetails.RAISE_ATTACK_DAMAGE_MULT, 40)],
                                        [[Effect(EffectTrigger.HEADS_HIT, EffectDetails.HEAL_FOR_DAMAGE, 50)]]),
                                  Skill("Dismember", Sin.SLOTH, 0, 6, 10, 1, [],  [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 5, status=StatusType.RUPTURE),
                                                                                    Effect(EffectTrigger.HEADS_HIT, EffectDetails.HEAL_FOR_DAMAGE, 50)]]),
                                  Skill("Eviscerate", Sin.LUST, 1, 4, 2, 4, [], [[Effect(EffectTrigger.BEFORE_HIT, EffectDetails.DEAL_PERCENT_BONUS_DAMAGE, 30, condition=[Condition(EffectCondition.TARGET_HAS_STATUS_OF_AMOUNT, condition_amount=1, condition_status=StatusType.RUPTURE)])],
                                                                                 [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.DEAL_PERCENT_BONUS_DAMAGE, 30, condition=[Condition(EffectCondition.TARGET_HAS_STATUS_OF_AMOUNT, condition_amount=1, condition_status=StatusType.RUPTURE)])],
                                                                                 [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.DEAL_PERCENT_BONUS_DAMAGE, 30, condition=[Condition(EffectCondition.TARGET_HAS_STATUS_OF_AMOUNT, condition_amount=1, condition_status=StatusType.RUPTURE)])],
                                                                                 [Effect(EffectTrigger.HEADS_HIT, EffectDetails.HEAL_FOR_DAMAGE, 100)]])]),
    "The One Who Grips Faust": Sinner("The One Who Grips Faust", 134, 4, 7, 31, 39, [50, 0, -25], [70, 40, 20],
                                 [Skill("Cackle", Sin.ENVY, 1, 4, 3, 2, [Effect(EffectTrigger.ClASH_WIN, EffectDetails.TARGET_LOSE_SP, 3)],
                                        [[Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT, 1, status=StatusType.NAILS)],
                                         [Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.BLEED)]]),
                                  Skill("The Gripping", Sin.LUST, 1, 4, 4, 3, [], [[], [Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT, 3, status=StatusType.NAILS)],
                                                                                   [Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS_NEXT_TURN, 1, status=StatusType.PARALYZE),
                                                                                    Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS_NEXT_TURN, 1, status=StatusType.GAZE)]]),
                                  Skill("Execution", Sin.PRIDE, 2, 6, 2, 3, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.APPLY_STATUS_COUNT, 2, status=StatusType.NAILS)], # TODO: Kill effect
                                                                                 [Effect(EffectTrigger.HEADS_HIT, EffectDetails.APPLY_STATUS_COUNT, 2, status=StatusType.NAILS)],
                                                                                 [Effect(EffectTrigger.BEFORE_HIT, EffectDetails.COIN_DMG_MULT, 50, condition=[Condition(EffectCondition.TARGET_HAS_STATUS_OF_COUNT, condition_amount=5, condition_status=StatusType.NAILS)])]])]),
    "W Corp. Cleanup Agent Don Quixote": Sinner("W Corp. Cleanup Agent Don Quixote", 148, 3, 6, 28, 38, [0, -25, 50], [70, 40, 20],
                                 [Skill("Rip", Sin.SLOTH, 0, 5, 6, 1, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.INFLICT_STATUS, 1, status=StatusType.RUPTURE),
                                                                           Effect(EffectTrigger.HEADS_HIT, EffectDetails.GAIN_STATUS_COUNT, 2, status=StatusType.CHARGE)]]),
                                  Skill("Leap", Sin.GLOOM, 1, 4, 4, 3, [], [[Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_COUNT, 4, status=StatusType.CHARGE)],
                                                                            [Effect(EffectTrigger.ON_HIT, EffectDetails.GAIN_STATUS_COUNT, 4, status=StatusType.CHARGE)],
                                                                            [Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 2, status=StatusType.FRAGILE)]]),
                                  Skill("Rip Space", Sin.ENVY, 0, 1, 2, 5, [Effect(EffectTrigger.ON_USE, EffectDetails.LOSE_PERCENT_HP, 0, condition=[Condition(EffectCondition.SELF_HAS_STATUS_BELOW_COUNT, condition_amount=10, condition_status=StatusType.CHARGE)]),
                                                                             Effect(EffectTrigger.ON_USE, EffectDetails.COIN_POWER, 4, condition=[Condition(EffectCondition.SPEND_CHARGE, condition_amount=10)])],
                                        [[], [], [], [], [Effect(EffectTrigger.HEADS_HIT, EffectDetails.INFLICT_STATUS, 5, status=StatusType.RUPTURE)]])]),
}